import 'package:cloud_firestore/cloud_firestore.dart';

/// Heurística: IDs automáticos do Firestore (~20 caracteres alfanuméricos).
bool churchDepartmentDocIdLooksAutoGenerated(String id) {
  final s = id.trim();
  if (s.length < 18 || s.length > 24) return false;
  return RegExp(r'^[a-zA-Z0-9]+$').hasMatch(s);
}

/// Campos Firestore/planilha que contam como “nome explícito” (para avisos na UI).
const List<String> kChurchDepartmentExplicitNameKeys = [
  'name',
  'nome',
  'NOME',
  'Name',
  'label',
  'title',
  'titulo',
  'TITULO',
  'departmentName',
  'nomeDepartamento',
  'nome_departamento',
  'displayName',
  'DEPARTAMENTO',
  'departamento',
  'Departamento',
  'descricao',
  'Descrição',
  'description',
];

/// `true` se algum campo tradicional de nome está preenchido (não é só fallback por id).
bool churchDepartmentDocHasExplicitNameField(Map<String, dynamic> m) {
  for (final key in kChurchDepartmentExplicitNameKeys) {
    if ((m[key] ?? '').toString().trim().isNotEmpty) return true;
  }
  return false;
}

/// Nome exibível do departamento — o app grava [name]; importações podem usar [nome], [label], etc.
/// [docId]: ids legíveis (`louvor`) viram título; ids auto do Firestore sem nome geram rótulo temporário
/// para o departamento **não sumir** do painel (antes a lista filtrava e ficava em branco).
String churchDepartmentNameFromData(
  Map<String, dynamic> m, {
  String? docId,
}) {
  for (final key in kChurchDepartmentExplicitNameKeys) {
    final v = (m[key] ?? '').toString().trim();
    if (v.isNotEmpty) return v;
  }
  final id = (docId ?? '').trim();
  if (id.isNotEmpty && !churchDepartmentDocIdLooksAutoGenerated(id)) {
    return id.replaceAll('_', ' ').trim();
  }
  if (id.isNotEmpty && churchDepartmentDocIdLooksAutoGenerated(id)) {
    final short = id.length >= 8 ? id.substring(0, 8) : id;
    return 'Departamento $short';
  }
  return '';
}

/// Conveniência: dados do snapshot + id.
String churchDepartmentNameFromDoc(QueryDocumentSnapshot<Map<String, dynamic>> d) {
  return churchDepartmentNameFromData(d.data(), docId: d.id);
}

/// Normaliza nome para comparar duplicatas (espaços, maiúsculas).
String normalizeChurchDepartmentNameKey(String name) {
  return name
      .trim()
      .toLowerCase()
      .replaceAll(RegExp(r'\s+'), ' ');
}

/// Exibe nome com capitalização amigável (ex.: "MOCIDADE" → "Mocidade").
String prettifyChurchDepartmentDisplayName(String raw) {
  final s = raw.trim();
  if (s.isEmpty) return raw;
  return s.split(RegExp(r'\s+')).map((w) {
    if (w.isEmpty) return w;
    if (w.length > 2 && w == w.toUpperCase()) {
      return '${w[0]}${w.substring(1).toLowerCase()}';
    }
    if (w.length == 1) return w.toUpperCase();
    return w[0].toUpperCase() + w.substring(1).toLowerCase();
  }).join(' ');
}

int _deptDocScore(QueryDocumentSnapshot<Map<String, dynamic>> d) {
  final m = d.data();
  var s = 0;
  if (m['isDefaultPreset'] == true) s += 1000;
  if ((m['iconKey'] ?? '').toString().trim().isNotEmpty) s += 100;
  if ((m['themeKey'] ?? '').toString().trim().isNotEmpty) s += 50;
  return s;
}

/// Departamento considerado inativo (UI + dedupe em Escalas).
bool churchDepartmentDocIsActive(Map<String, dynamic> m) {
  if (m['active'] is bool && m['active'] == false) return false;
  if (m['ativo'] is bool && m['ativo'] == false) return false;
  final st = (m['status'] ?? m['STATUS'] ?? '').toString().toLowerCase().trim();
  if (st == 'inativo' ||
      st == 'inactive' ||
      st == 'desativado' ||
      st == 'false') {
    return false;
  }
  if (m['visivel'] is bool && m['visivel'] == false) return false;
  if (m['visible'] is bool && m['visible'] == false) return false;
  return true;
}

/// Remove departamentos com o mesmo nome (após normalização), mantendo o doc mais “oficial”.
/// Usado em Escalas / filtros para não repetir "Auxiliares" etc. com IDs diferentes.
List<QueryDocumentSnapshot<Map<String, dynamic>>> dedupeChurchDepartmentDocuments(
  List<QueryDocumentSnapshot<Map<String, dynamic>>> docs,
) {
  final usable = docs.where((d) {
    final m = d.data();
    if (!churchDepartmentDocIsActive(m)) return false;
    final name = churchDepartmentNameFromDoc(d);
    return name.isNotEmpty;
  }).toList();

  final byKey = <String, QueryDocumentSnapshot<Map<String, dynamic>>>{};
  for (final d in usable) {
    final name = churchDepartmentNameFromDoc(d);
    final key = normalizeChurchDepartmentNameKey(name);
    final cur = byKey[key];
    if (cur == null || _deptDocScore(d) > _deptDocScore(cur)) {
      byKey[key] = d;
    }
  }
  final out = byKey.values.toList();
  out.sort((a, b) {
    final na = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(a));
    final nb = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(b));
    return na.compareTo(nb);
  });
  return out;
}
