import 'package:cloud_firestore/cloud_firestore.dart';

/// Heurística: IDs automáticos do Firestore (~20 caracteres alfanuméricos).
bool churchDepartmentDocIdLooksAutoGenerated(String id) {
  final s = id.trim();
  if (s.length < 18 || s.length > 24) return false;
  return RegExp(r'^[a-zA-Z0-9]+$').hasMatch(s);
}

/// Campos Firestore/planilha que contam como “nome explícito” (para avisos na UI).
const List<String> kChurchDepartmentExplicitNameKeys = [
  'name',
  'nome',
  'NOME',
  'Name',
  'label',
  'title',
  'titulo',
  'TITULO',
  'departmentName',
  'nomeDepartamento',
  'nome_departamento',
  'displayName',
  'DEPARTAMENTO',
  'departamento',
  'Departamento',
  'descricao',
  'Descrição',
  'description',
];

/// `true` se algum campo tradicional de nome está preenchido (não é só fallback por id).
bool churchDepartmentDocHasExplicitNameField(Map<String, dynamic> m) {
  for (final key in kChurchDepartmentExplicitNameKeys) {
    if ((m[key] ?? '').toString().trim().isNotEmpty) return true;
  }
  return false;
}

/// Nome exibível do departamento — o app grava [name]; importações podem usar [nome], [label], etc.
/// [docId]: ids legíveis (`louvor`) viram título; ids auto do Firestore sem nome geram rótulo temporário
/// para o departamento **não sumir** do painel (antes a lista filtrava e ficava em branco).
String churchDepartmentNameFromData(
  Map<String, dynamic> m, {
  String? docId,
}) {
  for (final key in kChurchDepartmentExplicitNameKeys) {
    final v = (m[key] ?? '').toString().trim();
    if (v.isNotEmpty) return v;
  }
  final id = (docId ?? '').trim();
  if (id.isNotEmpty && !churchDepartmentDocIdLooksAutoGenerated(id)) {
    return id.replaceAll('_', ' ').trim();
  }
  if (id.isNotEmpty && churchDepartmentDocIdLooksAutoGenerated(id)) {
    final short = id.length >= 8 ? id.substring(0, 8) : id;
    return 'Departamento $short';
  }
  // Último recurso: nunca devolver nome vazio se existir id de documento (evita lista dedupe vazia).
  if (id.isNotEmpty) {
    return id.replaceAll('_', ' ').trim().isNotEmpty
        ? id.replaceAll('_', ' ').trim()
        : 'Departamento';
  }
  return '';
}

/// Conveniência: dados do snapshot + id.
String churchDepartmentNameFromDoc(QueryDocumentSnapshot<Map<String, dynamic>> d) {
  return churchDepartmentNameFromData(d.data(), docId: d.id);
}

/// Normaliza nome para comparar duplicatas (espaços, maiúsculas).
String normalizeChurchDepartmentNameKey(String name) {
  return name
      .trim()
      .toLowerCase()
      .replaceAll(RegExp(r'\s+'), ' ');
}

/// Remove acentos comuns (pt/EN) para formar id de documento [a-z0-9_].
String churchDepartmentFoldAsciiForDocId(String input) {
  if (input.isEmpty) return '';
  const map = <String, String>{
    'á': 'a', 'à': 'a', 'ã': 'a', 'â': 'a', 'ä': 'a',
    'é': 'e', 'ê': 'e', 'è': 'e', 'ë': 'e',
    'í': 'i', 'ì': 'i', 'î': 'i', 'ï': 'i',
    'ó': 'o', 'ò': 'o', 'õ': 'o', 'ô': 'o', 'ö': 'o',
    'ú': 'u', 'ù': 'u', 'û': 'u', 'ü': 'u',
    'ç': 'c', 'ñ': 'n',
    'Á': 'a', 'À': 'a', 'Ã': 'a', 'Â': 'a', 'Ä': 'a',
    'É': 'e', 'Ê': 'e', 'È': 'e', 'Ë': 'e',
    'Í': 'i', 'Ì': 'i', 'Î': 'i', 'Ï': 'i',
    'Ó': 'o', 'Ò': 'o', 'Õ': 'o', 'Ô': 'o', 'Ö': 'o',
    'Ú': 'u', 'Ù': 'u', 'Û': 'u', 'Ü': 'u',
    'Ç': 'c', 'Ñ': 'n',
  };
  final buf = StringBuffer();
  for (final c in input.runes) {
    final ch = String.fromCharCode(c);
    buf.write(map[ch] ?? ch);
  }
  return buf.toString().toLowerCase();
}

/// Id estável alinhado aos presets (`louvor`, `varoes`) — não usa ID auto do Firestore.
String churchDepartmentStableDocIdCandidate(String name, String iconKey) {
  String slug(String raw) {
    var s = churchDepartmentFoldAsciiForDocId(raw.trim());
    s = s.replaceAll(RegExp(r'[^a-z0-9]+'), '_');
    s = s.replaceAll(RegExp(r'_+'), '_');
    s = s.replaceAll(RegExp(r'^_|_$'), '');
    return s;
  }

  var s = slug(iconKey.isNotEmpty ? iconKey : name);
  if (s.isEmpty) s = slug(name);
  if (s.isEmpty) return 'departamento';
  if (s.length > 120) s = s.substring(0, 120);
  return s;
}

/// Exibe nome com capitalização amigável (ex.: "MOCIDADE" → "Mocidade").
String prettifyChurchDepartmentDisplayName(String raw) {
  final s = raw.trim();
  if (s.isEmpty) return raw;
  return s.split(RegExp(r'\s+')).map((w) {
    if (w.isEmpty) return w;
    if (w.length > 2 && w == w.toUpperCase()) {
      return '${w[0]}${w.substring(1).toLowerCase()}';
    }
    if (w.length == 1) return w.toUpperCase();
    return w[0].toUpperCase() + w.substring(1).toLowerCase();
  }).join(' ');
}

int _deptDocScore(QueryDocumentSnapshot<Map<String, dynamic>> d) {
  final m = d.data();
  var s = 0;
  if (m['isDefaultPreset'] == true) s += 1000;
  if ((m['iconKey'] ?? '').toString().trim().isNotEmpty) s += 100;
  if ((m['themeKey'] ?? '').toString().trim().isNotEmpty) s += 50;
  return s;
}

/// Departamento considerado inativo (UI + dedupe em Escalas).
bool churchDepartmentDocIsActive(Map<String, dynamic> m) {
  if (m['active'] is bool && m['active'] == false) return false;
  if (m['ativo'] is bool && m['ativo'] == false) return false;
  final st = (m['status'] ?? m['STATUS'] ?? '').toString().toLowerCase().trim();
  if (st == 'inativo' ||
      st == 'inactive' ||
      st == 'desativado' ||
      st == 'false') {
    return false;
  }
  if (m['visivel'] is bool && m['visivel'] == false) return false;
  if (m['visible'] is bool && m['visible'] == false) return false;
  return true;
}

/// Remove departamentos com o mesmo nome (após normalização), mantendo o doc mais “oficial”.
/// Usado em Escalas / filtros para não repetir "Auxiliares" etc. com IDs diferentes.
List<QueryDocumentSnapshot<Map<String, dynamic>>> dedupeChurchDepartmentDocuments(
  List<QueryDocumentSnapshot<Map<String, dynamic>>> docs,
) {
  final usable = docs.where((d) {
    final m = d.data();
    if (!churchDepartmentDocIsActive(m)) return false;
    final name = churchDepartmentNameFromDoc(d);
    return name.isNotEmpty;
  }).toList();

  final byKey = <String, QueryDocumentSnapshot<Map<String, dynamic>>>{};
  for (final d in usable) {
    final name = churchDepartmentNameFromDoc(d);
    final key = normalizeChurchDepartmentNameKey(name);
    final cur = byKey[key];
    if (cur == null || _deptDocScore(d) > _deptDocScore(cur)) {
      byKey[key] = d;
    }
  }
  final out = byKey.values.toList();
  out.sort((a, b) {
    final na = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(a));
    final nb = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(b));
    return na.compareTo(nb);
  });
  return out;
}

bool _hubPreferDocId(QueryDocumentSnapshot<Map<String, dynamic>> a) {
  // Prefere ids canônicos (slug) a sufixos numéricos tipo jovens_2, criancas_3.
  return !RegExp(r'_\d+$').hasMatch(a.id);
}

/// Hub “Departamentos”: um card por nome exibível — evita lista em branco por duplicatas
/// e repetição visual (criancas + criancas_2). Mantém ativos e inativos; entre duplicatas
/// de nome, prefere preset, doc com mais metadados, ativo e id sem `_2`.
List<QueryDocumentSnapshot<Map<String, dynamic>>> dedupeChurchDepartmentDocumentsForHub(
  List<QueryDocumentSnapshot<Map<String, dynamic>>> docs,
) {
  final usable = docs.where((d) {
    final name = churchDepartmentNameFromDoc(d);
    return name.isNotEmpty;
  }).toList();

  final byKey = <String, QueryDocumentSnapshot<Map<String, dynamic>>>{};
  for (final d in usable) {
    final name = churchDepartmentNameFromDoc(d);
    final key = normalizeChurchDepartmentNameKey(name);
    final cur = byKey[key];
    if (cur == null) {
      byKey[key] = d;
      continue;
    }
    final sd = _deptDocScore(d);
    final sc = _deptDocScore(cur);
    if (sd != sc) {
      if (sd > sc) byKey[key] = d;
      continue;
    }
    final ad = churchDepartmentDocIsActive(d.data());
    final ac = churchDepartmentDocIsActive(cur.data());
    if (ad != ac) {
      if (ad) byKey[key] = d;
      continue;
    }
    final pd = _hubPreferDocId(d);
    final pc = _hubPreferDocId(cur);
    if (pd != pc) {
      if (pd) byKey[key] = d;
      continue;
    }
    if (d.id.length != cur.id.length) {
      if (d.id.length < cur.id.length) byKey[key] = d;
      continue;
    }
    if (d.id.compareTo(cur.id) < 0) byKey[key] = d;
  }
  final out = byKey.values.toList();
  out.sort((a, b) {
    final na = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(a));
    final nb = normalizeChurchDepartmentNameKey(churchDepartmentNameFromDoc(b));
    return na.compareTo(nb);
  });
  return out;
}
