// ignore_for_file: lines_longer_than_80_chars

/// Lista base enxuta (11 departamentos) para novas igrejas e botão “Instalar catálogo”.
/// [iconKey] mapeia ícones em [church_department_fa_icons] e opções em [DepartmentsPage].
const List<Map<String, dynamic>> kChurchDepartmentPresetRows = [
  {
    'key': 'pastoral',
    'label': 'Pastoral',
    'iconKey': 'pastoral',
    'c1': 0xFF0D47A1,
    'c2': 0xFF1976D2,
    'description': 'Direção espiritual e pastoreio',
  },
  {
    'key': 'louvor',
    'label': 'Louvor',
    'iconKey': 'louvor',
    'c1': 0xFFFF6F00,
    'c2': 0xFFFFA726,
    'description': 'Adoração e ministério de música',
  },
  {
    'key': 'jovens',
    'label': 'Jovens',
    'iconKey': 'jovens',
    'c1': 0xFFFF5722,
    'c2': 0xFFFF7043,
    'description': 'Ministério com jovens',
  },
  {
    'key': 'criancas',
    'label': 'Crianças',
    'iconKey': 'criancas',
    'c1': 0xFF00ACC1,
    'c2': 0xFF4DD0E1,
    'description': 'Ministério infantil',
  },
  {
    'key': 'evangelismo',
    'label': 'Evangelismo',
    'iconKey': 'evangelismo',
    'c1': 0xFF6A1B9A,
    'c2': 0xFFAB47BC,
    'description': 'Alcance e novos convertidos',
  },
  {
    'key': 'intercessao',
    'label': 'Intercessão',
    'iconKey': 'intercessao',
    'c1': 0xFFE53935,
    'c2': 0xFFFF5252,
    'description': 'Oração e intercessão',
  },
  {
    'key': 'media',
    'label': 'Mídia',
    'iconKey': 'media',
    'c1': 0xFF1565C0,
    'c2': 0xFF42A5F5,
    'description': 'Som, imagem e comunicação digital',
  },
  {
    'key': 'recepcao',
    'label': 'Recepção',
    'iconKey': 'recepcao',
    'c1': 0xFFFF9800,
    'c2': 0xFFFFB74D,
    'description': 'Boas-vindas e acolhimento',
  },
  {
    'key': 'finance',
    'label': 'Financeiro',
    'iconKey': 'finance',
    'c1': 0xFF37474F,
    'c2': 0xFF546E7A,
    'description': 'Recursos e tesouraria',
  },
  {
    'key': 'escola_biblica',
    'label': 'Escola Bíblica',
    'iconKey': 'escola_biblica',
    'c1': 0xFF00695C,
    'c2': 0xFF26A69A,
    'description': 'Ensino da Palavra e EBD',
  },
  {
    'key': 'varoes',
    'label': 'Varões',
    'iconKey': 'varoes',
    'c1': 0xFF283593,
    'c2': 0xFF3F51B5,
    'description': 'Ministério com homens',
  },
];
